/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name PORTE29 (number 17), LED
  @{ */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_FGPIO FGPIOE              /*!<@brief FGPIO peripheral base pointer */
#define BOARD_INITPINS_LED_GPIO GPIOE                /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_INIT_GPIO_VALUE 0U        /*!<@brief GPIO output initial state */
#define BOARD_INITPINS_LED_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_LED_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PORTE20 (number 9), A2-ADC0_SE0
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_VOLTAGE_PORT PORTE                /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_VOLTAGE_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_VOLTAGE_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB3 (number 38), J1[13]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SDA_TEMP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SDA_TEMP_PIN 3U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SDA_TEMP_PIN_MASK (1U << 3U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PORTB2 (number 37), J1[15]
  @{ */

/* Symbols to be used with PORT driver */
#define BOARD_INITPINS_SCL_TEMP_PORT PORTB               /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SCL_TEMP_PIN 2U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SCL_TEMP_PIN_MASK (1U << 2U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
